### ISSUE TITLE
Generate pdf files

### ISSUE THREAD

**Issue by ohoelske** [ahodelin/Bachmann_Archive#55]
Generate PDF files in Adobe Illustrator combining all subfigures into one PDF per figure.

**Comment by jessvasseur** [comment]
first versions added - see [442016b](https://github.com/ahodelin/Bachmann_Archive/commit/442016b43c261b6ebf40d015f5175b51976c9003)

**Comment by jessvasseur** [comment]
a few suggestions regarding the generated pdfs
- number figures corresponding to Bachmann et al. figures (otherwise confusing)
- links not working yet
- add more detailed description of figures, e.g. for Figure 4: top panel = SOCS3 overexpression (orange line), bottom panel = CIS overexpression (orange line) vs. wildtype (blue line) 
- include reference to SED-ML file used to generate the figure, e.g. [Fig4.sedml](https://github.com/ahodelin/Bachmann_Archive/blob/main/experiment/Fig4.sedml)
- naming convention for COMBINE archive, e.g. Fig4_tellurium_2021-06-28 (_Figx_software_date_).

_Figure 3 A and C from Bachmann et al. were reproduced using tellurium vers. 2.2.0 in the Jupyter
notebook interface CoLab (SEDML_Fig3_v1.ipynb). The plots shown here were generated using Fig4.sedml (link) and Bachmann2011.xml (link), illustrating the time course of the indicated molecules (simulation time 250 min)._

**Comment by ohoelske** [comment]
New pdf files for tellurium were added, see 

1. [83026b3](https://github.com/ahodelin/Bachmann_Archive/commit/83026b3abbe44bef414a5e1f0a001be03ebf06a7)
2. [73f65ca](https://github.com/ahodelin/Bachmann_Archive/commit/73f65ca1ba80a43f2ac788a550bec8771fcc2f9c)
3. [71d633a](https://github.com/ahodelin/Bachmann_Archive/commit/71d633a30ac295cdb46f9cca76e8a2eea5a69bad)
4. [2279dcb](https://github.com/ahodelin/Bachmann_Archive/commit/2279dcbb1eb724bf07c297f9110a7dae46fff843)
